name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependency_overrides:
  camera_android: ^0.10.0+3
  camera_avfoundation: ^0.9.8+6
  scrollable_positioned_list: ^0.3.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  camera: ^0.10.0+4
  path: ^1.8.2
  get: ^4.6.5
  flutter_local_notifications: ^12.0.2
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  flutter_typeahead: ^4.1.1
  carousel_slider: ^4.1.1
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.6
  universal_html: ^2.0.8
  universal_platform: ^1.0.0+1
  flutter_inappwebview: ^5.6.0+1
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  flutter_html: ^3.0.0-alpha.6
  url_launcher: ^6.1.6
  http: ^0.13.5
  pointer_interceptor: ^0.9.3+3
  phone_number: ^1.0.0
  cached_network_image: ^3.2.2
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+2
  share_plus: ^6.0.1
  flutter_launcher_icons: ^0.10.0
  shared_preferences: ^2.0.15
  fancy_snackbar:
    git:
      url: https://github.com/MR0100/fancy_snackbar.git
  firebase_crashlytics: ^3.0.2
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  firebase_auth: ^4.0.2
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  flutter_contacts: ^1.1.5
  azlistview: ^2.0.0
  modal_bottom_sheet: ^2.1.2
  slide_to_confirm: ^1.1.0
  lottie: ^1.4.2
  expandable_bottom_sheet: ^1.1.1+1
  smooth_page_indicator: ^1.0.0+2
  webview_flutter: ^3.0.4
  flutter_svg: ^1.1.5
  device_preview: ^1.1.0
  shimmer: ^2.0.0
  permission_handler: ^10.1.0
  screenshot: ^1.2.3
  gallery_saver: ^2.3.2
  modal_progress_hud_nsn: ^0.3.0
  path_drawing: ^1.0.1
  currency_text_input_formatter: ^2.1.7
  flutter_custom_tabs: ^1.0.4
  local_auth: ^2.1.2
  google_mlkit_barcode_scanning: ^0.4.0
  google_mlkit_face_detection: ^0.4.0
  flutter_secure_storage: ^6.0.0
  app_settings: ^4.1.8
  percent_indicator: ^4.2.2
  cloud_firestore: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/animationFile/

  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/font/NotoSerif-Regular.ttf
          weight: 400
        - asset: assets/font/NotoSerif-Regular.ttf
          weight: 500
        - asset: assets/font/NotoSerif-Bold.ttf
          weight: 700
        - asset: assets/font/NotoSerif-Bold.ttf
          weight: 900
