name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get: ^4.6.5
  shared_preferences: ^2.0.15
  connectivity_plus: ^3.0.2
  flutter_local_notifications: ^9.7.0
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.1
  google_maps_flutter: ^2.1.10
  google_maps_flutter_web: ^0.4.0+1
  flutter_typeahead: ^4.0.0
  carousel_slider: ^4.1.1
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.5+3
  universal_html: ^2.0.8
  universal_platform: ^1.0.0-nullsafety
  flutter_inappwebview: ^5.4.3+7
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  flutter_html: ^3.0.0-alpha.5
  url_launcher: ^6.1.5
  http: ^0.13.4
  pointer_interceptor: ^0.9.3+2
  phone_number: ^0.12.0+2
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+2
  share_plus: ^4.0.10
  flutter_launcher_icons: ^0.9.3
  firebase_ui_auth: ^1.0.2
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/location_gh.png"
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900