name: sixam_mart
description: A Multi-vendor Food. Grocery, eCommerce, Pharmacy & Parcel service.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.10.0+4
  path: ^1.8.2
  get: ^4.6.5
  flutter_local_notifications: ^12.0.2
  path_provider: ^2.0.11
  url_strategy: ^0.2.0
  pin_code_fields: ^7.4.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  flutter_typeahead: ^4.1.1
  carousel_slider: ^4.1.1
  shimmer_animation: ^2.1.0+1
  image_picker: ^0.8.6
  universal_html: ^2.0.8
#  universal_ui: ^0.0.8
  universal_platform: ^1.0.0+1
  flutter_inappwebview: ^5.6.0+1
  flutter_widget_from_html: ^0.8.5
  fwfh_selectable_text: ^0.8.3+1
  flutter_html: ^3.0.0-alpha.6
  url_launcher: ^6.1.6
  http: ^0.13.5
  pointer_interceptor: ^0.9.3+3
  phone_number: ^1.0.0
  cached_network_image: ^3.2.2
#  google_sign_in: ^5.2.1
#  flutter_facebook_auth: ^3.5.7
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+2
  share_plus: ^6.0.1
  flutter_launcher_icons: ^0.10.0
  shared_preferences: ^2.0.15
  fancy_snackbar:
    git:
      url: https://github.com/MR0100/fancy_snackbar.git
  firebase_crashlytics: ^3.0.2
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  firebase_auth: ^4.0.2
  connectivity_plus: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900
