// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrmpidZP3RpzTdqJ4yjPDYVXxEc4F6Km0',
    appId: '1:977332047026:web:8d15fac1ae7940322f4dab',
    messagingSenderId: '977332047026',
    projectId: 'zopay-e17da',
    authDomain: 'zopay-e17da.firebaseapp.com',
    storageBucket: 'zopay-e17da.appspot.com',
    measurementId: 'G-CRYL6323NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1sswvFkexF72r2-UWCwPM1vPmW_QHo84',
    appId: '1:977332047026:android:a01fd47e4bcb6a2a2f4dab',
    messagingSenderId: '977332047026',
    projectId: 'zopay-e17da',
    storageBucket: 'zopay-e17da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByyP1j7JoXUs1wE92n8Dh1fD9WzdxvwnI',
    appId: '1:977332047026:ios:6d079ce7fc7efbd82f4dab',
    messagingSenderId: '977332047026',
    projectId: 'zopay-e17da',
    storageBucket: 'zopay-e17da.appspot.com',
    androidClientId: '977332047026-3edsjk9tjp48udc2qppuppi8aql1tjj9.apps.googleusercontent.com',
    iosClientId: '977332047026-rvfl60ak6ouhrb3rirm5koond7ts20vv.apps.googleusercontent.com',
    iosBundleId: 'com.sixamtech.sixamMart',
  );
}
